### ISSUE TITLE
Hardware configuration requirements

### ISSUE THREAD

**Issue by jjjxusbx** [subbu963/bott#1]
![屏幕截图 2023-12-27 002602](https://github.com/subbu963/bott/assets/146902099/8935a160-cfd8-4dde-9b8a-5aaae23f7a12)
Please ask if the hardware configuration of the above picture can run successfullybot-in-terminal

**Comment by subbu963** [comment]
You should be able to run

For ollama, codellama 7b model you need atleast 8gb

For openai, RAM required is minimal(probably 100mb)

**Comment by subbu963** [comment]
Closing this for now. Let me know if you still need help
